name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: T3mmyKay
          template: classic
          
          # "Contributions" are part of 'activity'. 
          # 'header' adds your name/profile picture.
          base: header, activity
          config_timezone: Africa/Lagos
          
          # "Most used languages"
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
